### ISSUE TITLE
Refactor how checkpoints are detected with player cars

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#95]
Currently, the car notifies the Race Session Manager on passing through a checkpoint (including the finish line checkpoint). 

It's not the car's responsibility to keep track of the race state (which the checkpoints are inherently tied to). It should be the other way around, such that the checkpoints detect when a player car crosses it.

**Comment by RFSurdsman** [comment]
Create a script and add it to the Checkpoint child game object under each track. It must be in the checkpoint game object, because that is where the collider lives (collision messages are not send upwards to the parent if the object doesn't have a rigidbody. Track pieces don't have rigidbodies once they have been generated as they are supposed to be static un-movable objects in the world). 

Move the OnTriggerEnter code in the Car Manager to this new script. Now the track piece notifies the server race state when the player passes through the checkpoint,.
